### ISSUE TITLE
Please release a version of this library with valid license metadata

### ISSUE THREAD

**Issue by mrwilby** [aliyun/alibabacloud-dkms-transfer-java-sdk#13]
The library appears to be licensed using apache 2 terms, but the metadata inside pom.xml is not valid:

https://github.com/aliyun/alibabacloud-dkms-transfer-java-sdk/blob/master/sdk/pom.xml#L55

Please release a new version of this library with valid metadata. Thanks

**Comment by yingzhi-aliyun** [comment]
The apache version 2   license had been added in the pom file.
